// winmm_proxy - DLL Proxy generated by X-Toolkit
// Target: winmm.dll (x86)
// Generated: Mon Apr 27 23:53:44 2026
//

#include <windows.h>
#include <type_traits>
#include <utility>
#include <cstdint>

// 默认使用 TLS 回调尽早修补导出桩。
// 如需改为 DllMain 初始化：
// 1. 注释掉下面这行
// 2. 在 dllmain.cpp 中声明并调用：extern void InitializeProxyStubs();
#define USE_TLS_CALLBACK_INIT

// 兼容性：尽量使用 feature-test macros（比仅判断语言标准版本号更可靠）
// 注意：本模板目标覆盖 C++11-23，因此语法级差异仍需少量 #if 分支。

#if defined(_MSC_VER)
#  define DLLPROXY_NORETURN __declspec(noreturn)
#else
#  define DLLPROXY_NORETURN __attribute__((noreturn))
#endif

#if defined(_MSC_VER)
    #define DLLPROXY_ALIGN(N) __declspec(align(N))
#else
    #define DLLPROXY_ALIGN(N) alignas(N)
#endif

#if defined(__cpp_constinit)
    #define DLLPROXY_CONSTINIT constinit
#else
    #define DLLPROXY_CONSTINIT
#endif

namespace proxy_detail {
    template<bool B, typename T = void>
    struct enable_if { };

    template<typename T>
    struct enable_if<true, T> { typedef T type; };

    template<bool B, typename T = void>
    using enable_if_t = typename enable_if<B, T>::type;

#if defined(__cpp_lib_is_invocable)
    template<typename F, typename... Args>
    struct is_invocable : std::is_invocable<F, Args...> {};
#else
    template<typename F, typename... Args>
    struct is_invocable {
        template<typename U>
        static auto test(int) -> decltype(std::declval<U>()(std::declval<Args>()...), std::true_type{}) { return {}; }
        template<typename>
        static auto test(...) -> std::false_type { return {}; }
        using type = decltype(test<F>(0));
        static const bool value = type::value;
    };
#endif
}

// 功能：代理初始化失败原因枚举（ErrorCode）
// 触发时机：代理初始化/修补 stub 过程中发生不可恢复错误
// 原理：UnrecoverableError 会根据错误码弹窗提示，并终止进程，避免代理处于"部分初始化"状态继续运行
// 关键点：
//   - 代理属于底层转发组件，失败后继续运行可能导致崩溃或误转发，因此选择 Fail-Fast
enum class ErrorCode : std::uint8_t {
    InvalidModuleBase    = 0, // 无法获取当前代理 DLL 的模块句柄
    InvalidModuleHeaders = 1, // 当前模块 PE 头/导出表结构异常
    VirtualProtectFailed = 2, // 修改 stub 区域内存保护属性失败
    LibraryNotFound      = 3, // 无法加载原始 DLL（系统/相对路径）
    ExportNotFound       = 4, // 在原始 DLL 中找不到对应导出（名称/序号均失败）
    ExportNotResolved    = 5, // stub 在尚未修补前被调用（理论上不应发生）
};

// 函数声明
void              UnresolvedExportCallback();
DLLPROXY_NORETURN void UnrecoverableError(ErrorCode code);
HMODULE           GetCurrentModuleHandle();
void              ShowFatalProxyErrorAndExit(ErrorCode code);
bool              ResolveOriginalExport(void* module, uint32_t ordinal, const char* name, void** functionPointer);
HMODULE           LoadOriginalModule();

// 功能：自定义节与对齐设置（stub 区域标记）
// 触发时机：模块加载时常量初始化
// 原理：
//   - 为所有 stub 定义一个单独的节 .dllprox
//   - ExportRegionStart / ExportRegionEnd 用于标记 stub 区域在内存中的起止地址
//   - InitializeProxyStubs 会通过这些边界判断某个导出是否为"代理桩"
constexpr size_t DefaultPageAlign = 4096; // 与页面对齐，方便 VirtualProtect
constexpr size_t DefaultFuncAlign = 16;   // stub 对齐（函数入口对齐）

#pragma section(".dllprox$a", read)
DLLPROXY_ALIGN(DefaultPageAlign) __declspec(allocate(".dllprox$a"))
DLLPROXY_CONSTINIT uint8_t ExportRegionStart = 1;

#pragma section(".dllprox$b", read)
#pragma section(".dllprox$z", read)
DLLPROXY_ALIGN(DefaultPageAlign) __declspec(allocate(".dllprox$z"))
DLLPROXY_CONSTINIT uint8_t ExportRegionEnd = 1;

// 将 .dllprox 合并进 .text，避免生成多余节。
#pragma comment(linker, "/MERGE:.dllprox=.text")

// 功能：导出桩（stub）结构定义
// 触发时机：编译期定义；运行期由 InitializeProxyStubs 写入 TargetAddress
// 原理：
//   - 为每个导出生成一个可修补的跳转桩；
//   - InitializeProxyStubs 会把 TargetAddress 填成原始 DLL 的真实导出地址；
//   - x64/x86 机器码布局不同，但 TargetAddress 字段语义一致：最终跳转目标地址。
//
// x64：jmp qword ptr [rip+imm32]
//   FF 25                       ; JmpIndirectOpcode
//   imm32                       ; RipRelativeDisplacement（RIP 相对位移，指向 TargetAddress）
//   8-byte ptr (TargetAddress)  ; TargetAddress（运行时修补为真实函数地址）
//   Padding (2 字节)            ; 保证 16 字节对齐
//
// x86：jmp dword ptr [imm32]
//   FF 25                       ; JmpIndirectOpcode
//   imm32 (ptr to TargetAddress); TargetPointerAddress（跳转表项地址：CPU 会从该地址读取 TargetAddress）
//   4-byte ptr (TargetAddress)  ; TargetAddress（运行时修补为真实函数地址）
//   Padding (6 字节)            ; 保证 16 字节对齐
#if defined(_WIN64) || defined(__x86_64__) || defined(__LP64__) || defined(_M_X64)
#pragma pack(push, 1)
struct X64Stub {
    uint8_t JmpIndirectOpcode[2];    // FF 25
    int32_t RipRelativeDisplacement; // imm32：RIP 相对位移（指向 TargetAddress 字段）
    void*   TargetAddress;           // [rip+imm32] 实际会读取这里的指针；运行时写入真实函数地址
    uint8_t Padding[2];              // 填充，使整体大小为 16 字节
};
static_assert(sizeof(X64Stub) == 16, "X64Stub 期望 16 字节");
#pragma pack(pop)
using X64StubType = struct X64Stub;
#else
#pragma pack(push, 1)
struct X86Stub {
    uint8_t JmpIndirectOpcode[2]; // FF 25
    void*   TargetPointerAddress; // imm32：绝对地址（指向 TargetAddress 字段的位置）
    void*   TargetAddress;        // 跳转表项内容；运行时写入真实函数地址
    uint8_t Padding[6];           // 填充，使整体大小为 16 字节
};
static_assert(sizeof(X86Stub) == 16, "X86Stub 期望 16 字节");
#pragma pack(pop)
using X86StubType = struct X86Stub;
#endif

// 功能：处理不可恢复错误（Fail-Fast）
// 触发时机：代理初始化/导出解析/修补过程中发生异常
// 原理：弹窗提示 + TerminateProcess 直接终止进程，避免代理处于"部分初始化"状态继续运行
// 关键点：
//   - 这里不抛异常、不返回错误码：因为 proxy 属于底层转发组件，继续运行风险更大
DLLPROXY_NORETURN __declspec(noinline) void UnrecoverableError(ErrorCode code) {
    ShowFatalProxyErrorAndExit(code);
    __debugbreak();
    __assume(0);
}

// 功能：未修补导出桩的兜底回调
// 触发时机：某个导出桩在 InitializeProxyStubs 修补前就被调用（理论上不应发生）
// 原理：直接触发 UnrecoverableError(ExportNotResolved)
void UnresolvedExportCallback() {
    UnrecoverableError(ErrorCode::ExportNotResolved);
}

// 功能：显示致命错误并退出进程
// 触发时机：UnrecoverableError 调用
// 原理：尝试调用 user32!MessageBoxW 提示错误码，随后 TerminateProcess 强制退出
// 关键点：
//   - 使用 LoadLibrary/GetProcAddress 动态加载 MessageBoxW，避免额外依赖
//   - TerminateProcess 退出码包含固定标记 + 错误码，便于定位
void ShowFatalProxyErrorAndExit(ErrorCode code) {
    if (const HMODULE user32 = LoadLibraryW(L"user32.dll")) {
        const auto messageBox = reinterpret_cast<decltype(&MessageBoxW)>(
            GetProcAddress(user32, "MessageBoxW")
        );
        if (messageBox) {
            wchar_t reason[] = L"代理 DLL 初始化失败，错误代码: 0";
            reason[(sizeof(reason) / sizeof(reason[0])) - 2] =
                L'0' + static_cast<uint8_t>(code);
            messageBox(nullptr, reason, L"代理 DLL 致命错误", MB_ICONERROR);
        }
    }
    TerminateProcess(GetCurrentProcess(), 0xBADC0DE0 | static_cast<uint8_t>(code));
}

// 功能：获取当前代理 DLL 的模块句柄（带缓存）
// 触发时机：运行期首次需要做 RVA->VA 或获取自身路径等
// 原理：GetModuleHandleExW + GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS，用自己的函数地址反推出 HMODULE
// 关键点：
//   - 不能用 GetModuleHandleW(NULL)，它返回宿主 EXE
//   - GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT：不增加引用计数，避免影响卸载行为
//   - 用 Interlocked 做一次性缓存初始化，避免并发初始化

__declspec(noinline)
HMODULE GetCurrentModuleHandle() {
    DLLPROXY_CONSTINIT static HMODULE volatile g_CachedModule = nullptr;

    HMODULE h = reinterpret_cast<HMODULE>(
        InterlockedCompareExchangePointer(
            reinterpret_cast<PVOID volatile*>(&g_CachedModule),
            nullptr,
            nullptr
        )
    );
    if (!h) {
        const DWORD flags = GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
                            GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT;
        HMODULE handle = nullptr;
        if (!GetModuleHandleExW(flags,
                                reinterpret_cast<LPCWSTR>(&GetCurrentModuleHandle),
                                &handle)) {
            UnrecoverableError(ErrorCode::InvalidModuleBase);
        }
        PVOID prev = InterlockedExchangePointer(
            reinterpret_cast<PVOID volatile*>(&g_CachedModule),
            handle
        );
        h = prev ? reinterpret_cast<HMODULE>(prev) : handle;
    }
    return h;
}

// 功能：将当前模块内 RVA 转换为 VA（RvaToVa）
// 触发时机：解析 PE 头/导出表时（EnumerateCurrentModuleExports）
// 原理：VA = moduleBase + RVA；若 T 为指针类型则 reinterpret_cast，否则按整数返回
// 关键点：
//   - 该函数依赖 GetCurrentModuleHandle 获取当前代理 DLL 的模块基址
// 返回：转换后的 VA（指针或整数）
// 使用模板分派分别处理指针和非指针类型（兼容 C++11-23）
template<typename T>
T RvaToVa_impl(uintptr_t base, std::true_type) {
    return reinterpret_cast<T>(base);
}

template<typename T>
T RvaToVa_impl(uintptr_t base, std::false_type) {
    return static_cast<T>(base);
}

template<typename T>
T RvaToVa(uintptr_t rva) {
    auto base = reinterpret_cast<uintptr_t>(GetCurrentModuleHandle()) + rva;
    return RvaToVa_impl<T>(base, std::is_pointer<T>{});
}

// 功能：枚举当前模块导出（对仅序号导出/无名称表情况安全）
// 触发时机：InitializeProxyStubs 修补阶段
// 原理：解析当前模块导出表，逐一回调（ordinal/name/address）
// 关键点：
//   - 这里对 PE 头与导出表做必要校验，发现异常直接 Fail-Fast
//   - 为保持模板简单，对名称的查找使用线性扫描（O(N^2)），对常见系统 DLL 足够
// 返回：无（通过 callback 返回每个导出）

template<typename TCallback, typename = proxy_detail::enable_if_t<
    proxy_detail::is_invocable<TCallback, uint32_t, const char*, uintptr_t>::value
>>
void EnumerateCurrentModuleExports(TCallback&& callback) {
    // 基本 PE 头校验：如果代理 DLL 被破坏/被错误加载，应尽早失败
    const auto dos = RvaToVa<const IMAGE_DOS_HEADER*>(0);
    if (!dos || dos->e_magic != IMAGE_DOS_SIGNATURE)
        UnrecoverableError(ErrorCode::InvalidModuleHeaders);

    const auto nt = RvaToVa<const IMAGE_NT_HEADERS*>(dos->e_lfanew);
    if (!nt || nt->Signature != IMAGE_NT_SIGNATURE)
        UnrecoverableError(ErrorCode::InvalidModuleHeaders);

    const auto& opt = nt->OptionalHeader;
    // 兼容 x86/x64 两种 OptionalHeader 魔数
    if (!(opt.Magic == IMAGE_NT_OPTIONAL_HDR32_MAGIC ||
          opt.Magic == IMAGE_NT_OPTIONAL_HDR64_MAGIC))
        UnrecoverableError(ErrorCode::InvalidModuleHeaders);

    // DataDirectory 数组必须包含导出表
    if (opt.NumberOfRvaAndSizes <= IMAGE_DIRECTORY_ENTRY_EXPORT)
        UnrecoverableError(ErrorCode::InvalidModuleHeaders);

    const auto& dir = opt.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT];
    // 导出表必须存在且大小合理
    if (dir.VirtualAddress == 0 || dir.Size < sizeof(IMAGE_EXPORT_DIRECTORY))
        UnrecoverableError(ErrorCode::InvalidModuleHeaders);

    const auto exp = RvaToVa<const IMAGE_EXPORT_DIRECTORY*>(dir.VirtualAddress);
    // 导出表中必须有函数表
    if (!exp || exp->AddressOfFunctions == 0 || exp->NumberOfFunctions == 0)
        UnrecoverableError(ErrorCode::InvalidModuleHeaders);

    const auto funcRvaTable = RvaToVa<const uint32_t*>(exp->AddressOfFunctions);

    const uint32_t nameCount = exp->NumberOfNames;
    const bool hasNames = (nameCount > 0) &&
                          (exp->AddressOfNames != 0) &&
                          (exp->AddressOfNameOrdinals != 0);

    const uint32_t* nameRvaTable = nullptr;
    const uint16_t* nameOrdinals = nullptr;
    if (hasNames) {
        nameRvaTable = RvaToVa<const uint32_t*>(exp->AddressOfNames);
        nameOrdinals = RvaToVa<const uint16_t*>(exp->AddressOfNameOrdinals);
    }

    for (uint32_t i = 0; i < exp->NumberOfFunctions; ++i) {
        const uint32_t exportOrdinal = exp->Base + i;
        const char* exportName = nullptr;

        // 导出名表只包含“有名称的导出”，需要通过 nameOrdinals 反查当前函数索引 i 对应的名字
        if (hasNames && nameRvaTable && nameOrdinals) {
            for (uint32_t j = 0; j < nameCount; ++j) {
                if (nameOrdinals[j] == i) {
                    exportName = RvaToVa<const char*>(nameRvaTable[j]);
                    break;
                }
            }
        }

        callback(exportOrdinal, exportName, RvaToVa<uintptr_t>(funcRvaTable[i]));
    }
}

// 功能：解析原始 DLL 的真实导出地址（名称 + 序号）
// 触发时机：InitializeProxyStubs 修补每个桩时
// 原理：
//   - 先按名称解析：存在名称导出时更精确
//   - 再按序号解析：兼容仅序号导出或名称缺失
// 返回：true 表示成功写入 *functionPointer

bool ResolveOriginalExport(void* module,
                           uint32_t ordinal,
                           const char* name,
                           void** functionPointer) {
    void* ptr = nullptr;

    // 先按名称解析（更精确）
    if (name) {
        ptr = reinterpret_cast<void*>(
            GetProcAddress(static_cast<HMODULE>(module), name)
        );
    }
    // 再按序号解析（兼容仅序号导出）
    if (!ptr) {
        ptr = reinterpret_cast<void*>(
            GetProcAddress(static_cast<HMODULE>(module), MAKEINTRESOURCEA(ordinal))
        );
    }

    if (!ptr) return false;
    *functionPointer = ptr;
    return true;
}

// 功能：修补 stub（把代理桩指向原始 DLL 的真实导出）
// 触发时机：TLS 回调 DLL_PROCESS_ATTACH
// 原理：
//   - 加载原始 DLL
//   - VirtualProtect 将 stub 区域改为可写（通常合并到 .text 默认不可写）
//   - 遍历当前 DLL 的导出表，筛选出位于 stub 区域内的导出
//   - 逐个解析原始导出地址，写入 stub->TargetAddress
//   - 恢复内存保护并 FlushInstructionCache

#if defined(_WIN64) || defined(__x86_64__) || defined(__LP64__) || defined(_M_X64)
void InitializeProxyStubs() {
    const auto original = LoadOriginalModule();
    if (!original) UnrecoverableError(ErrorCode::LibraryNotFound);

    const auto regionStart = reinterpret_cast<uintptr_t>(&ExportRegionStart);
    const auto regionEnd   = reinterpret_cast<uintptr_t>(&ExportRegionEnd);
    const auto regionSize  = regionEnd - regionStart;
    DWORD oldProt = 0;

    // 将 stub 区域临时改为可写（通常位于合并后的 .text）
    if (!VirtualProtect(reinterpret_cast<void*>(regionStart),
        regionSize, PAGE_READWRITE, &oldProt)) {
        UnrecoverableError(ErrorCode::VirtualProtectFailed);
    }

    EnumerateCurrentModuleExports(
        [&](uint32_t ordinal, const char* name, uintptr_t address) {
            // 仅修补位于 stub 区域内的导出
            if (address > regionStart && address < regionEnd) {
                void* resolved = nullptr;
                if (!ResolveOriginalExport(original, ordinal, name, &resolved) ||
                    !resolved) {
                    UnrecoverableError(ErrorCode::ExportNotFound);
                }

                auto* stub = reinterpret_cast<X64StubType*>(address);
#ifdef _DEBUG
                // 理论上每个 stub 都是 DefaultFuncAlign 对齐；调试版多做一次防御性检查
                if (reinterpret_cast<uintptr_t>(stub) % DefaultFuncAlign != 0) {
                    UnrecoverableError(ErrorCode::InvalidModuleBase);
                }
#endif
                stub->TargetAddress = resolved;
            }
        });

    // 恢复原始页面保护
    if (!VirtualProtect(reinterpret_cast<void*>(regionStart),
                        regionSize,
                        oldProt,
                        &oldProt)) {
        UnrecoverableError(ErrorCode::VirtualProtectFailed);
    }

    // 刷新指令缓存，避免 CPU 继续使用旧缓存
    FlushInstructionCache(GetCurrentProcess(),
                          reinterpret_cast<void*>(regionStart),
                          regionSize);
}
#else  // x86 分支
void InitializeProxyStubs() {
    const auto original = LoadOriginalModule();
    if (!original)
        UnrecoverableError(ErrorCode::LibraryNotFound);

    const auto regionStart = reinterpret_cast<uintptr_t>(&ExportRegionStart);
    const auto regionEnd   = reinterpret_cast<uintptr_t>(&ExportRegionEnd);
    const auto regionSize  = regionEnd - regionStart;
    DWORD oldProt = 0;

    // 将 stub 区域临时改为可写（通常位于合并后的 .text）
    if (!VirtualProtect(reinterpret_cast<void*>(regionStart),
                        regionSize,
                        PAGE_READWRITE,
                        &oldProt)) {
        UnrecoverableError(ErrorCode::VirtualProtectFailed);
    }

    EnumerateCurrentModuleExports(
        [&](uint32_t ordinal, const char* name, uintptr_t address) {
            if (address > regionStart && address < regionEnd) {
                void* resolved = nullptr;
                if (!ResolveOriginalExport(original, ordinal, name, &resolved) ||
                    !resolved) {
                    UnrecoverableError(ErrorCode::ExportNotFound);
                }

                auto* stub = reinterpret_cast<X86StubType*>(address);
#ifdef _DEBUG
                if (reinterpret_cast<uintptr_t>(stub) % DefaultFuncAlign != 0) {
                    UnrecoverableError(ErrorCode::InvalidModuleBase);
                }
#endif
                stub->TargetAddress = resolved;
            }
        });

    // 恢复原始页面保护
    if (!VirtualProtect(reinterpret_cast<void*>(regionStart),
                        regionSize,
                        oldProt,
                        &oldProt)) {
        UnrecoverableError(ErrorCode::VirtualProtectFailed);
    }

    FlushInstructionCache(GetCurrentProcess(),
                          reinterpret_cast<void*>(regionStart),
                          regionSize);
}
#endif  // 架构分支

// ----------------------------------------
// TLS 回调：在 DLL_PROCESS_ATTACH 时自动调用 InitializeProxyStubs
//
// 说明：
//  - 使用 TLS 回调是为了尽早执行 stub 修补，尽量保证首次导出调用前完成初始化；
//  - TLS 回调仍处于模块加载阶段，不是“脱离 Loader Lock”的通用安全区，因此这里的逻辑要保持克制。
// ----------------------------------------
#ifdef USE_TLS_CALLBACK_INIT
void WINAPI ProxyTLSInitCallback(PVOID /*dllHandle*/, DWORD reason, PVOID) {
    if (reason == DLL_PROCESS_ATTACH)
        InitializeProxyStubs();
}
#if defined(_WIN64) || defined(__x86_64__) || defined(__LP64__) || defined(_M_X64)
// 将 TLS 回调指针放入 .CRT$XLB 段，参与 C 运行时初始化
#pragma const_seg(push, proxconst, ".CRT$XLB")
extern "C" __declspec(selectany) const PIMAGE_TLS_CALLBACK DllProxyTLSCallback = ProxyTLSInitCallback;
#pragma const_seg(pop, proxconst)
#pragma comment(linker, "/INCLUDE:_tls_used")
#pragma comment(linker, "/INCLUDE:DllProxyTLSCallback")
#else
#pragma data_seg(push, proxdata, ".CRT$XLB")
extern "C" __declspec(selectany) PIMAGE_TLS_CALLBACK DllProxyTLSCallback = ProxyTLSInitCallback;
#pragma data_seg(pop, proxdata)
#pragma comment(linker, "/INCLUDE:__tls_used")
#pragma comment(linker, "/INCLUDE:_DllProxyTLSCallback")
#endif
#endif // USE_TLS_CALLBACK_INIT

// 功能：加载原始 DLL（系统目录版本）
// 触发时机：InitializeProxyStubs 调用时
// 原理：
//   - x64：从 %SystemRoot%\System32\winmm.dll 加载；
//   - x86：在 64 位系统上从 %SystemRoot%\SysWOW64\winmm.dll 加载；若不存在 Wow64 目录，则回退到 32 位系统的 System32。
// 关键点：
//   - 使用 InitOnce + g_OriginalModule，避免重复 LoadLibraryW；
//   - 加载失败会弹窗提示（用于验证/排错）。
static INIT_ONCE g_LoadOriginalModuleOnce = INIT_ONCE_STATIC_INIT;
static HMODULE g_OriginalModule = nullptr;

static BOOL CALLBACK InitOriginalModule(PINIT_ONCE /*once*/, PVOID /*parameter*/, PVOID* /*context*/) {
    if (g_OriginalModule) {
        return TRUE;
    }

    wchar_t path[MAX_PATH];
    SecureZeroMemory(path, sizeof(path));

#if defined(_WIN64) || defined(__x86_64__) || defined(__LP64__) || defined(_M_X64)
    GetSystemDirectoryW(path, MAX_PATH);
#else
    // 32 位进程在 64 位系统上应加载 SysWOW64；若该目录不存在，则视为 32 位系统并回退到 System32
    if (GetSystemWow64DirectoryW(path, MAX_PATH) == 0) {
        GetSystemDirectoryW(path, MAX_PATH);
    }
#endif

    wcscat_s(path, MAX_PATH, L"\\");
    wcscat_s(path, MAX_PATH, L"winmm.dll");

    g_OriginalModule = LoadLibraryW(path);
    if (!g_OriginalModule) {
        MessageBoxW(nullptr,
                    L"无法加载原始模块 winmm.dll",
                    L"DLL 代理",
                    MB_ICONSTOP);
    }

    return g_OriginalModule != nullptr;
}

HMODULE LoadOriginalModule() {
    InitOnceExecuteOnce(&g_LoadOriginalModuleOnce, InitOriginalModule, nullptr, nullptr);
    return g_OriginalModule;
}

// 功能：导出桩定义（Export Stubs）
// 触发时机：编译期生成；运行期由 InitializeProxyStubs 修补
// 原理：
//   - 每个 X64Stub/X86Stub 对应一个导出函数的代理桩；
//   - 生成时：TargetAddress 初始指向 UnresolvedExportCallback（防止未初始化就被调用）；
//   - 初始化时：InitializeProxyStubs 解析原始 DLL 的真实导出地址，并修补 TargetAddress。
// 关键点：
//   - x64/x86 stub 机器码布局不同，但 TargetAddress 语义一致：最终跳转目标地址；
//   - 通过 #pragma comment(linker, "/EXPORT:...@...") 声明导出名称和序号。
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_1 { {0xFF, 0x25}, (void*)&XPROXY_1.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_1=_XPROXY_1")
#pragma comment(linker, "/EXPORT:2=XPROXY_1,@2,NONAME")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_2 { {0xFF, 0x25}, (void*)&XPROXY_2.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_2=_XPROXY_2")
#pragma comment(linker, "/EXPORT:mciExecute=XPROXY_2,@3")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_3 { {0xFF, 0x25}, (void*)&XPROXY_3.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_3=_XPROXY_3")
#pragma comment(linker, "/EXPORT:CloseDriver=XPROXY_3,@4")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_4 { {0xFF, 0x25}, (void*)&XPROXY_4.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_4=_XPROXY_4")
#pragma comment(linker, "/EXPORT:DefDriverProc=XPROXY_4,@5")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_5 { {0xFF, 0x25}, (void*)&XPROXY_5.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_5=_XPROXY_5")
#pragma comment(linker, "/EXPORT:DriverCallback=XPROXY_5,@6")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_6 { {0xFF, 0x25}, (void*)&XPROXY_6.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_6=_XPROXY_6")
#pragma comment(linker, "/EXPORT:DrvGetModuleHandle=XPROXY_6,@7")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_7 { {0xFF, 0x25}, (void*)&XPROXY_7.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_7=_XPROXY_7")
#pragma comment(linker, "/EXPORT:GetDriverModuleHandle=XPROXY_7,@8")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_8 { {0xFF, 0x25}, (void*)&XPROXY_8.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_8=_XPROXY_8")
#pragma comment(linker, "/EXPORT:NotifyCallbackData=XPROXY_8,@9")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_9 { {0xFF, 0x25}, (void*)&XPROXY_9.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_9=_XPROXY_9")
#pragma comment(linker, "/EXPORT:OpenDriver=XPROXY_9,@10")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_10 { {0xFF, 0x25}, (void*)&XPROXY_10.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_10=_XPROXY_10")
#pragma comment(linker, "/EXPORT:PlaySound=XPROXY_10,@11")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_11 { {0xFF, 0x25}, (void*)&XPROXY_11.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_11=_XPROXY_11")
#pragma comment(linker, "/EXPORT:PlaySoundA=XPROXY_11,@12")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_12 { {0xFF, 0x25}, (void*)&XPROXY_12.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_12=_XPROXY_12")
#pragma comment(linker, "/EXPORT:PlaySoundW=XPROXY_12,@13")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_13 { {0xFF, 0x25}, (void*)&XPROXY_13.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_13=_XPROXY_13")
#pragma comment(linker, "/EXPORT:SendDriverMessage=XPROXY_13,@14")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_14 { {0xFF, 0x25}, (void*)&XPROXY_14.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_14=_XPROXY_14")
#pragma comment(linker, "/EXPORT:WOW32DriverCallback=XPROXY_14,@15")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_15 { {0xFF, 0x25}, (void*)&XPROXY_15.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_15=_XPROXY_15")
#pragma comment(linker, "/EXPORT:WOW32ResolveMultiMediaHandle=XPROXY_15,@16")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_16 { {0xFF, 0x25}, (void*)&XPROXY_16.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_16=_XPROXY_16")
#pragma comment(linker, "/EXPORT:WOWAppExit=XPROXY_16,@17")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_17 { {0xFF, 0x25}, (void*)&XPROXY_17.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_17=_XPROXY_17")
#pragma comment(linker, "/EXPORT:aux32Message=XPROXY_17,@18")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_18 { {0xFF, 0x25}, (void*)&XPROXY_18.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_18=_XPROXY_18")
#pragma comment(linker, "/EXPORT:auxGetDevCapsA=XPROXY_18,@19")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_19 { {0xFF, 0x25}, (void*)&XPROXY_19.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_19=_XPROXY_19")
#pragma comment(linker, "/EXPORT:auxGetDevCapsW=XPROXY_19,@20")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_20 { {0xFF, 0x25}, (void*)&XPROXY_20.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_20=_XPROXY_20")
#pragma comment(linker, "/EXPORT:auxGetNumDevs=XPROXY_20,@21")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_21 { {0xFF, 0x25}, (void*)&XPROXY_21.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_21=_XPROXY_21")
#pragma comment(linker, "/EXPORT:auxGetVolume=XPROXY_21,@22")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_22 { {0xFF, 0x25}, (void*)&XPROXY_22.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_22=_XPROXY_22")
#pragma comment(linker, "/EXPORT:auxOutMessage=XPROXY_22,@23")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_23 { {0xFF, 0x25}, (void*)&XPROXY_23.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_23=_XPROXY_23")
#pragma comment(linker, "/EXPORT:auxSetVolume=XPROXY_23,@24")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_24 { {0xFF, 0x25}, (void*)&XPROXY_24.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_24=_XPROXY_24")
#pragma comment(linker, "/EXPORT:joy32Message=XPROXY_24,@25")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_25 { {0xFF, 0x25}, (void*)&XPROXY_25.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_25=_XPROXY_25")
#pragma comment(linker, "/EXPORT:joyConfigChanged=XPROXY_25,@26")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_26 { {0xFF, 0x25}, (void*)&XPROXY_26.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_26=_XPROXY_26")
#pragma comment(linker, "/EXPORT:joyGetDevCapsA=XPROXY_26,@27")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_27 { {0xFF, 0x25}, (void*)&XPROXY_27.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_27=_XPROXY_27")
#pragma comment(linker, "/EXPORT:joyGetDevCapsW=XPROXY_27,@28")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_28 { {0xFF, 0x25}, (void*)&XPROXY_28.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_28=_XPROXY_28")
#pragma comment(linker, "/EXPORT:joyGetNumDevs=XPROXY_28,@29")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_29 { {0xFF, 0x25}, (void*)&XPROXY_29.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_29=_XPROXY_29")
#pragma comment(linker, "/EXPORT:joyGetPos=XPROXY_29,@30")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_30 { {0xFF, 0x25}, (void*)&XPROXY_30.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_30=_XPROXY_30")
#pragma comment(linker, "/EXPORT:joyGetPosEx=XPROXY_30,@31")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_31 { {0xFF, 0x25}, (void*)&XPROXY_31.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_31=_XPROXY_31")
#pragma comment(linker, "/EXPORT:joyGetThreshold=XPROXY_31,@32")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_32 { {0xFF, 0x25}, (void*)&XPROXY_32.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_32=_XPROXY_32")
#pragma comment(linker, "/EXPORT:joyReleaseCapture=XPROXY_32,@33")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_33 { {0xFF, 0x25}, (void*)&XPROXY_33.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_33=_XPROXY_33")
#pragma comment(linker, "/EXPORT:joySetCapture=XPROXY_33,@34")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_34 { {0xFF, 0x25}, (void*)&XPROXY_34.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_34=_XPROXY_34")
#pragma comment(linker, "/EXPORT:joySetThreshold=XPROXY_34,@35")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_35 { {0xFF, 0x25}, (void*)&XPROXY_35.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_35=_XPROXY_35")
#pragma comment(linker, "/EXPORT:mci32Message=XPROXY_35,@36")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_36 { {0xFF, 0x25}, (void*)&XPROXY_36.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_36=_XPROXY_36")
#pragma comment(linker, "/EXPORT:mciDriverNotify=XPROXY_36,@37")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_37 { {0xFF, 0x25}, (void*)&XPROXY_37.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_37=_XPROXY_37")
#pragma comment(linker, "/EXPORT:mciDriverYield=XPROXY_37,@38")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_38 { {0xFF, 0x25}, (void*)&XPROXY_38.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_38=_XPROXY_38")
#pragma comment(linker, "/EXPORT:mciFreeCommandResource=XPROXY_38,@39")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_39 { {0xFF, 0x25}, (void*)&XPROXY_39.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_39=_XPROXY_39")
#pragma comment(linker, "/EXPORT:mciGetCreatorTask=XPROXY_39,@40")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_40 { {0xFF, 0x25}, (void*)&XPROXY_40.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_40=_XPROXY_40")
#pragma comment(linker, "/EXPORT:mciGetDeviceIDA=XPROXY_40,@41")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_41 { {0xFF, 0x25}, (void*)&XPROXY_41.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_41=_XPROXY_41")
#pragma comment(linker, "/EXPORT:mciGetDeviceIDFromElementIDA=XPROXY_41,@42")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_42 { {0xFF, 0x25}, (void*)&XPROXY_42.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_42=_XPROXY_42")
#pragma comment(linker, "/EXPORT:mciGetDeviceIDFromElementIDW=XPROXY_42,@43")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_43 { {0xFF, 0x25}, (void*)&XPROXY_43.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_43=_XPROXY_43")
#pragma comment(linker, "/EXPORT:mciGetDeviceIDW=XPROXY_43,@44")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_44 { {0xFF, 0x25}, (void*)&XPROXY_44.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_44=_XPROXY_44")
#pragma comment(linker, "/EXPORT:mciGetDriverData=XPROXY_44,@45")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_45 { {0xFF, 0x25}, (void*)&XPROXY_45.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_45=_XPROXY_45")
#pragma comment(linker, "/EXPORT:mciGetErrorStringA=XPROXY_45,@46")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_46 { {0xFF, 0x25}, (void*)&XPROXY_46.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_46=_XPROXY_46")
#pragma comment(linker, "/EXPORT:mciGetErrorStringW=XPROXY_46,@47")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_47 { {0xFF, 0x25}, (void*)&XPROXY_47.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_47=_XPROXY_47")
#pragma comment(linker, "/EXPORT:mciGetYieldProc=XPROXY_47,@48")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_48 { {0xFF, 0x25}, (void*)&XPROXY_48.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_48=_XPROXY_48")
#pragma comment(linker, "/EXPORT:mciLoadCommandResource=XPROXY_48,@49")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_49 { {0xFF, 0x25}, (void*)&XPROXY_49.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_49=_XPROXY_49")
#pragma comment(linker, "/EXPORT:mciSendCommandA=XPROXY_49,@50")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_50 { {0xFF, 0x25}, (void*)&XPROXY_50.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_50=_XPROXY_50")
#pragma comment(linker, "/EXPORT:mciSendCommandW=XPROXY_50,@51")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_51 { {0xFF, 0x25}, (void*)&XPROXY_51.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_51=_XPROXY_51")
#pragma comment(linker, "/EXPORT:mciSendStringA=XPROXY_51,@52")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_52 { {0xFF, 0x25}, (void*)&XPROXY_52.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_52=_XPROXY_52")
#pragma comment(linker, "/EXPORT:mciSendStringW=XPROXY_52,@53")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_53 { {0xFF, 0x25}, (void*)&XPROXY_53.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_53=_XPROXY_53")
#pragma comment(linker, "/EXPORT:mciSetDriverData=XPROXY_53,@54")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_54 { {0xFF, 0x25}, (void*)&XPROXY_54.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_54=_XPROXY_54")
#pragma comment(linker, "/EXPORT:mciSetYieldProc=XPROXY_54,@55")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_55 { {0xFF, 0x25}, (void*)&XPROXY_55.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_55=_XPROXY_55")
#pragma comment(linker, "/EXPORT:mid32Message=XPROXY_55,@56")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_56 { {0xFF, 0x25}, (void*)&XPROXY_56.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_56=_XPROXY_56")
#pragma comment(linker, "/EXPORT:midiConnect=XPROXY_56,@57")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_57 { {0xFF, 0x25}, (void*)&XPROXY_57.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_57=_XPROXY_57")
#pragma comment(linker, "/EXPORT:midiDisconnect=XPROXY_57,@58")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_58 { {0xFF, 0x25}, (void*)&XPROXY_58.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_58=_XPROXY_58")
#pragma comment(linker, "/EXPORT:midiInAddBuffer=XPROXY_58,@59")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_59 { {0xFF, 0x25}, (void*)&XPROXY_59.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_59=_XPROXY_59")
#pragma comment(linker, "/EXPORT:midiInClose=XPROXY_59,@60")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_60 { {0xFF, 0x25}, (void*)&XPROXY_60.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_60=_XPROXY_60")
#pragma comment(linker, "/EXPORT:midiInGetDevCapsA=XPROXY_60,@61")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_61 { {0xFF, 0x25}, (void*)&XPROXY_61.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_61=_XPROXY_61")
#pragma comment(linker, "/EXPORT:midiInGetDevCapsW=XPROXY_61,@62")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_62 { {0xFF, 0x25}, (void*)&XPROXY_62.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_62=_XPROXY_62")
#pragma comment(linker, "/EXPORT:midiInGetErrorTextA=XPROXY_62,@63")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_63 { {0xFF, 0x25}, (void*)&XPROXY_63.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_63=_XPROXY_63")
#pragma comment(linker, "/EXPORT:midiInGetErrorTextW=XPROXY_63,@64")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_64 { {0xFF, 0x25}, (void*)&XPROXY_64.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_64=_XPROXY_64")
#pragma comment(linker, "/EXPORT:midiInGetID=XPROXY_64,@65")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_65 { {0xFF, 0x25}, (void*)&XPROXY_65.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_65=_XPROXY_65")
#pragma comment(linker, "/EXPORT:midiInGetNumDevs=XPROXY_65,@66")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_66 { {0xFF, 0x25}, (void*)&XPROXY_66.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_66=_XPROXY_66")
#pragma comment(linker, "/EXPORT:midiInMessage=XPROXY_66,@67")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_67 { {0xFF, 0x25}, (void*)&XPROXY_67.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_67=_XPROXY_67")
#pragma comment(linker, "/EXPORT:midiInOpen=XPROXY_67,@68")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_68 { {0xFF, 0x25}, (void*)&XPROXY_68.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_68=_XPROXY_68")
#pragma comment(linker, "/EXPORT:midiInPrepareHeader=XPROXY_68,@69")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_69 { {0xFF, 0x25}, (void*)&XPROXY_69.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_69=_XPROXY_69")
#pragma comment(linker, "/EXPORT:midiInReset=XPROXY_69,@70")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_70 { {0xFF, 0x25}, (void*)&XPROXY_70.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_70=_XPROXY_70")
#pragma comment(linker, "/EXPORT:midiInStart=XPROXY_70,@71")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_71 { {0xFF, 0x25}, (void*)&XPROXY_71.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_71=_XPROXY_71")
#pragma comment(linker, "/EXPORT:midiInStop=XPROXY_71,@72")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_72 { {0xFF, 0x25}, (void*)&XPROXY_72.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_72=_XPROXY_72")
#pragma comment(linker, "/EXPORT:midiInUnprepareHeader=XPROXY_72,@73")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_73 { {0xFF, 0x25}, (void*)&XPROXY_73.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_73=_XPROXY_73")
#pragma comment(linker, "/EXPORT:midiOutCacheDrumPatches=XPROXY_73,@74")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_74 { {0xFF, 0x25}, (void*)&XPROXY_74.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_74=_XPROXY_74")
#pragma comment(linker, "/EXPORT:midiOutCachePatches=XPROXY_74,@75")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_75 { {0xFF, 0x25}, (void*)&XPROXY_75.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_75=_XPROXY_75")
#pragma comment(linker, "/EXPORT:midiOutClose=XPROXY_75,@76")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_76 { {0xFF, 0x25}, (void*)&XPROXY_76.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_76=_XPROXY_76")
#pragma comment(linker, "/EXPORT:midiOutGetDevCapsA=XPROXY_76,@77")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_77 { {0xFF, 0x25}, (void*)&XPROXY_77.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_77=_XPROXY_77")
#pragma comment(linker, "/EXPORT:midiOutGetDevCapsW=XPROXY_77,@78")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_78 { {0xFF, 0x25}, (void*)&XPROXY_78.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_78=_XPROXY_78")
#pragma comment(linker, "/EXPORT:midiOutGetErrorTextA=XPROXY_78,@79")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_79 { {0xFF, 0x25}, (void*)&XPROXY_79.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_79=_XPROXY_79")
#pragma comment(linker, "/EXPORT:midiOutGetErrorTextW=XPROXY_79,@80")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_80 { {0xFF, 0x25}, (void*)&XPROXY_80.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_80=_XPROXY_80")
#pragma comment(linker, "/EXPORT:midiOutGetID=XPROXY_80,@81")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_81 { {0xFF, 0x25}, (void*)&XPROXY_81.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_81=_XPROXY_81")
#pragma comment(linker, "/EXPORT:midiOutGetNumDevs=XPROXY_81,@82")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_82 { {0xFF, 0x25}, (void*)&XPROXY_82.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_82=_XPROXY_82")
#pragma comment(linker, "/EXPORT:midiOutGetVolume=XPROXY_82,@83")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_83 { {0xFF, 0x25}, (void*)&XPROXY_83.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_83=_XPROXY_83")
#pragma comment(linker, "/EXPORT:midiOutLongMsg=XPROXY_83,@84")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_84 { {0xFF, 0x25}, (void*)&XPROXY_84.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_84=_XPROXY_84")
#pragma comment(linker, "/EXPORT:midiOutMessage=XPROXY_84,@85")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_85 { {0xFF, 0x25}, (void*)&XPROXY_85.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_85=_XPROXY_85")
#pragma comment(linker, "/EXPORT:midiOutOpen=XPROXY_85,@86")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_86 { {0xFF, 0x25}, (void*)&XPROXY_86.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_86=_XPROXY_86")
#pragma comment(linker, "/EXPORT:midiOutPrepareHeader=XPROXY_86,@87")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_87 { {0xFF, 0x25}, (void*)&XPROXY_87.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_87=_XPROXY_87")
#pragma comment(linker, "/EXPORT:midiOutReset=XPROXY_87,@88")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_88 { {0xFF, 0x25}, (void*)&XPROXY_88.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_88=_XPROXY_88")
#pragma comment(linker, "/EXPORT:midiOutSetVolume=XPROXY_88,@89")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_89 { {0xFF, 0x25}, (void*)&XPROXY_89.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_89=_XPROXY_89")
#pragma comment(linker, "/EXPORT:midiOutShortMsg=XPROXY_89,@90")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_90 { {0xFF, 0x25}, (void*)&XPROXY_90.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_90=_XPROXY_90")
#pragma comment(linker, "/EXPORT:midiOutUnprepareHeader=XPROXY_90,@91")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_91 { {0xFF, 0x25}, (void*)&XPROXY_91.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_91=_XPROXY_91")
#pragma comment(linker, "/EXPORT:midiStreamClose=XPROXY_91,@92")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_92 { {0xFF, 0x25}, (void*)&XPROXY_92.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_92=_XPROXY_92")
#pragma comment(linker, "/EXPORT:midiStreamOpen=XPROXY_92,@93")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_93 { {0xFF, 0x25}, (void*)&XPROXY_93.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_93=_XPROXY_93")
#pragma comment(linker, "/EXPORT:midiStreamOut=XPROXY_93,@94")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_94 { {0xFF, 0x25}, (void*)&XPROXY_94.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_94=_XPROXY_94")
#pragma comment(linker, "/EXPORT:midiStreamPause=XPROXY_94,@95")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_95 { {0xFF, 0x25}, (void*)&XPROXY_95.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_95=_XPROXY_95")
#pragma comment(linker, "/EXPORT:midiStreamPosition=XPROXY_95,@96")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_96 { {0xFF, 0x25}, (void*)&XPROXY_96.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_96=_XPROXY_96")
#pragma comment(linker, "/EXPORT:midiStreamProperty=XPROXY_96,@97")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_97 { {0xFF, 0x25}, (void*)&XPROXY_97.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_97=_XPROXY_97")
#pragma comment(linker, "/EXPORT:midiStreamRestart=XPROXY_97,@98")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_98 { {0xFF, 0x25}, (void*)&XPROXY_98.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_98=_XPROXY_98")
#pragma comment(linker, "/EXPORT:midiStreamStop=XPROXY_98,@99")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_99 { {0xFF, 0x25}, (void*)&XPROXY_99.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_99=_XPROXY_99")
#pragma comment(linker, "/EXPORT:mixerClose=XPROXY_99,@100")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_100 { {0xFF, 0x25}, (void*)&XPROXY_100.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_100=_XPROXY_100")
#pragma comment(linker, "/EXPORT:mixerGetControlDetailsA=XPROXY_100,@101")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_101 { {0xFF, 0x25}, (void*)&XPROXY_101.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_101=_XPROXY_101")
#pragma comment(linker, "/EXPORT:mixerGetControlDetailsW=XPROXY_101,@102")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_102 { {0xFF, 0x25}, (void*)&XPROXY_102.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_102=_XPROXY_102")
#pragma comment(linker, "/EXPORT:mixerGetDevCapsA=XPROXY_102,@103")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_103 { {0xFF, 0x25}, (void*)&XPROXY_103.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_103=_XPROXY_103")
#pragma comment(linker, "/EXPORT:mixerGetDevCapsW=XPROXY_103,@104")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_104 { {0xFF, 0x25}, (void*)&XPROXY_104.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_104=_XPROXY_104")
#pragma comment(linker, "/EXPORT:mixerGetID=XPROXY_104,@105")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_105 { {0xFF, 0x25}, (void*)&XPROXY_105.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_105=_XPROXY_105")
#pragma comment(linker, "/EXPORT:mixerGetLineControlsA=XPROXY_105,@106")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_106 { {0xFF, 0x25}, (void*)&XPROXY_106.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_106=_XPROXY_106")
#pragma comment(linker, "/EXPORT:mixerGetLineControlsW=XPROXY_106,@107")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_107 { {0xFF, 0x25}, (void*)&XPROXY_107.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_107=_XPROXY_107")
#pragma comment(linker, "/EXPORT:mixerGetLineInfoA=XPROXY_107,@108")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_108 { {0xFF, 0x25}, (void*)&XPROXY_108.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_108=_XPROXY_108")
#pragma comment(linker, "/EXPORT:mixerGetLineInfoW=XPROXY_108,@109")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_109 { {0xFF, 0x25}, (void*)&XPROXY_109.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_109=_XPROXY_109")
#pragma comment(linker, "/EXPORT:mixerGetNumDevs=XPROXY_109,@110")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_110 { {0xFF, 0x25}, (void*)&XPROXY_110.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_110=_XPROXY_110")
#pragma comment(linker, "/EXPORT:mixerMessage=XPROXY_110,@111")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_111 { {0xFF, 0x25}, (void*)&XPROXY_111.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_111=_XPROXY_111")
#pragma comment(linker, "/EXPORT:mixerOpen=XPROXY_111,@112")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_112 { {0xFF, 0x25}, (void*)&XPROXY_112.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_112=_XPROXY_112")
#pragma comment(linker, "/EXPORT:mixerSetControlDetails=XPROXY_112,@113")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_113 { {0xFF, 0x25}, (void*)&XPROXY_113.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_113=_XPROXY_113")
#pragma comment(linker, "/EXPORT:mmDrvInstall=XPROXY_113,@114")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_114 { {0xFF, 0x25}, (void*)&XPROXY_114.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_114=_XPROXY_114")
#pragma comment(linker, "/EXPORT:mmGetCurrentTask=XPROXY_114,@115")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_115 { {0xFF, 0x25}, (void*)&XPROXY_115.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_115=_XPROXY_115")
#pragma comment(linker, "/EXPORT:mmTaskBlock=XPROXY_115,@116")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_116 { {0xFF, 0x25}, (void*)&XPROXY_116.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_116=_XPROXY_116")
#pragma comment(linker, "/EXPORT:mmTaskCreate=XPROXY_116,@117")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_117 { {0xFF, 0x25}, (void*)&XPROXY_117.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_117=_XPROXY_117")
#pragma comment(linker, "/EXPORT:mmTaskSignal=XPROXY_117,@118")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_118 { {0xFF, 0x25}, (void*)&XPROXY_118.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_118=_XPROXY_118")
#pragma comment(linker, "/EXPORT:mmTaskYield=XPROXY_118,@119")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_119 { {0xFF, 0x25}, (void*)&XPROXY_119.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_119=_XPROXY_119")
#pragma comment(linker, "/EXPORT:mmioAdvance=XPROXY_119,@120")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_120 { {0xFF, 0x25}, (void*)&XPROXY_120.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_120=_XPROXY_120")
#pragma comment(linker, "/EXPORT:mmioAscend=XPROXY_120,@121")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_121 { {0xFF, 0x25}, (void*)&XPROXY_121.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_121=_XPROXY_121")
#pragma comment(linker, "/EXPORT:mmioClose=XPROXY_121,@122")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_122 { {0xFF, 0x25}, (void*)&XPROXY_122.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_122=_XPROXY_122")
#pragma comment(linker, "/EXPORT:mmioCreateChunk=XPROXY_122,@123")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_123 { {0xFF, 0x25}, (void*)&XPROXY_123.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_123=_XPROXY_123")
#pragma comment(linker, "/EXPORT:mmioDescend=XPROXY_123,@124")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_124 { {0xFF, 0x25}, (void*)&XPROXY_124.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_124=_XPROXY_124")
#pragma comment(linker, "/EXPORT:mmioFlush=XPROXY_124,@125")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_125 { {0xFF, 0x25}, (void*)&XPROXY_125.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_125=_XPROXY_125")
#pragma comment(linker, "/EXPORT:mmioGetInfo=XPROXY_125,@126")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_126 { {0xFF, 0x25}, (void*)&XPROXY_126.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_126=_XPROXY_126")
#pragma comment(linker, "/EXPORT:mmioInstallIOProcA=XPROXY_126,@127")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_127 { {0xFF, 0x25}, (void*)&XPROXY_127.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_127=_XPROXY_127")
#pragma comment(linker, "/EXPORT:mmioInstallIOProcW=XPROXY_127,@128")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_128 { {0xFF, 0x25}, (void*)&XPROXY_128.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_128=_XPROXY_128")
#pragma comment(linker, "/EXPORT:mmioOpenA=XPROXY_128,@129")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_129 { {0xFF, 0x25}, (void*)&XPROXY_129.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_129=_XPROXY_129")
#pragma comment(linker, "/EXPORT:mmioOpenW=XPROXY_129,@130")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_130 { {0xFF, 0x25}, (void*)&XPROXY_130.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_130=_XPROXY_130")
#pragma comment(linker, "/EXPORT:mmioRead=XPROXY_130,@131")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_131 { {0xFF, 0x25}, (void*)&XPROXY_131.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_131=_XPROXY_131")
#pragma comment(linker, "/EXPORT:mmioRenameA=XPROXY_131,@132")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_132 { {0xFF, 0x25}, (void*)&XPROXY_132.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_132=_XPROXY_132")
#pragma comment(linker, "/EXPORT:mmioRenameW=XPROXY_132,@133")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_133 { {0xFF, 0x25}, (void*)&XPROXY_133.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_133=_XPROXY_133")
#pragma comment(linker, "/EXPORT:mmioSeek=XPROXY_133,@134")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_134 { {0xFF, 0x25}, (void*)&XPROXY_134.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_134=_XPROXY_134")
#pragma comment(linker, "/EXPORT:mmioSendMessage=XPROXY_134,@135")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_135 { {0xFF, 0x25}, (void*)&XPROXY_135.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_135=_XPROXY_135")
#pragma comment(linker, "/EXPORT:mmioSetBuffer=XPROXY_135,@136")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_136 { {0xFF, 0x25}, (void*)&XPROXY_136.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_136=_XPROXY_136")
#pragma comment(linker, "/EXPORT:mmioSetInfo=XPROXY_136,@137")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_137 { {0xFF, 0x25}, (void*)&XPROXY_137.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_137=_XPROXY_137")
#pragma comment(linker, "/EXPORT:mmioStringToFOURCCA=XPROXY_137,@138")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_138 { {0xFF, 0x25}, (void*)&XPROXY_138.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_138=_XPROXY_138")
#pragma comment(linker, "/EXPORT:mmioStringToFOURCCW=XPROXY_138,@139")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_139 { {0xFF, 0x25}, (void*)&XPROXY_139.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_139=_XPROXY_139")
#pragma comment(linker, "/EXPORT:mmioWrite=XPROXY_139,@140")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_140 { {0xFF, 0x25}, (void*)&XPROXY_140.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_140=_XPROXY_140")
#pragma comment(linker, "/EXPORT:mmsystemGetVersion=XPROXY_140,@141")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_141 { {0xFF, 0x25}, (void*)&XPROXY_141.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_141=_XPROXY_141")
#pragma comment(linker, "/EXPORT:mod32Message=XPROXY_141,@142")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_142 { {0xFF, 0x25}, (void*)&XPROXY_142.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_142=_XPROXY_142")
#pragma comment(linker, "/EXPORT:mxd32Message=XPROXY_142,@143")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_143 { {0xFF, 0x25}, (void*)&XPROXY_143.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_143=_XPROXY_143")
#pragma comment(linker, "/EXPORT:sndPlaySoundA=XPROXY_143,@144")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_144 { {0xFF, 0x25}, (void*)&XPROXY_144.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_144=_XPROXY_144")
#pragma comment(linker, "/EXPORT:sndPlaySoundW=XPROXY_144,@145")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_145 { {0xFF, 0x25}, (void*)&XPROXY_145.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_145=_XPROXY_145")
#pragma comment(linker, "/EXPORT:tid32Message=XPROXY_145,@146")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_146 { {0xFF, 0x25}, (void*)&XPROXY_146.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_146=_XPROXY_146")
#pragma comment(linker, "/EXPORT:timeBeginPeriod=XPROXY_146,@147")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_147 { {0xFF, 0x25}, (void*)&XPROXY_147.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_147=_XPROXY_147")
#pragma comment(linker, "/EXPORT:timeEndPeriod=XPROXY_147,@148")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_148 { {0xFF, 0x25}, (void*)&XPROXY_148.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_148=_XPROXY_148")
#pragma comment(linker, "/EXPORT:timeGetDevCaps=XPROXY_148,@149")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_149 { {0xFF, 0x25}, (void*)&XPROXY_149.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_149=_XPROXY_149")
#pragma comment(linker, "/EXPORT:timeGetSystemTime=XPROXY_149,@150")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_150 { {0xFF, 0x25}, (void*)&XPROXY_150.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_150=_XPROXY_150")
#pragma comment(linker, "/EXPORT:timeGetTime=XPROXY_150,@151")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_151 { {0xFF, 0x25}, (void*)&XPROXY_151.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_151=_XPROXY_151")
#pragma comment(linker, "/EXPORT:timeKillEvent=XPROXY_151,@152")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_152 { {0xFF, 0x25}, (void*)&XPROXY_152.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_152=_XPROXY_152")
#pragma comment(linker, "/EXPORT:timeSetEvent=XPROXY_152,@153")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_153 { {0xFF, 0x25}, (void*)&XPROXY_153.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_153=_XPROXY_153")
#pragma comment(linker, "/EXPORT:waveInAddBuffer=XPROXY_153,@154")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_154 { {0xFF, 0x25}, (void*)&XPROXY_154.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_154=_XPROXY_154")
#pragma comment(linker, "/EXPORT:waveInClose=XPROXY_154,@155")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_155 { {0xFF, 0x25}, (void*)&XPROXY_155.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_155=_XPROXY_155")
#pragma comment(linker, "/EXPORT:waveInGetDevCapsA=XPROXY_155,@156")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_156 { {0xFF, 0x25}, (void*)&XPROXY_156.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_156=_XPROXY_156")
#pragma comment(linker, "/EXPORT:waveInGetDevCapsW=XPROXY_156,@157")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_157 { {0xFF, 0x25}, (void*)&XPROXY_157.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_157=_XPROXY_157")
#pragma comment(linker, "/EXPORT:waveInGetErrorTextA=XPROXY_157,@158")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_158 { {0xFF, 0x25}, (void*)&XPROXY_158.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_158=_XPROXY_158")
#pragma comment(linker, "/EXPORT:waveInGetErrorTextW=XPROXY_158,@159")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_159 { {0xFF, 0x25}, (void*)&XPROXY_159.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_159=_XPROXY_159")
#pragma comment(linker, "/EXPORT:waveInGetID=XPROXY_159,@160")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_160 { {0xFF, 0x25}, (void*)&XPROXY_160.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_160=_XPROXY_160")
#pragma comment(linker, "/EXPORT:waveInGetNumDevs=XPROXY_160,@161")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_161 { {0xFF, 0x25}, (void*)&XPROXY_161.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_161=_XPROXY_161")
#pragma comment(linker, "/EXPORT:waveInGetPosition=XPROXY_161,@162")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_162 { {0xFF, 0x25}, (void*)&XPROXY_162.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_162=_XPROXY_162")
#pragma comment(linker, "/EXPORT:waveInMessage=XPROXY_162,@163")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_163 { {0xFF, 0x25}, (void*)&XPROXY_163.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_163=_XPROXY_163")
#pragma comment(linker, "/EXPORT:waveInOpen=XPROXY_163,@164")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_164 { {0xFF, 0x25}, (void*)&XPROXY_164.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_164=_XPROXY_164")
#pragma comment(linker, "/EXPORT:waveInPrepareHeader=XPROXY_164,@165")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_165 { {0xFF, 0x25}, (void*)&XPROXY_165.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_165=_XPROXY_165")
#pragma comment(linker, "/EXPORT:waveInReset=XPROXY_165,@166")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_166 { {0xFF, 0x25}, (void*)&XPROXY_166.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_166=_XPROXY_166")
#pragma comment(linker, "/EXPORT:waveInStart=XPROXY_166,@167")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_167 { {0xFF, 0x25}, (void*)&XPROXY_167.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_167=_XPROXY_167")
#pragma comment(linker, "/EXPORT:waveInStop=XPROXY_167,@168")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_168 { {0xFF, 0x25}, (void*)&XPROXY_168.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_168=_XPROXY_168")
#pragma comment(linker, "/EXPORT:waveInUnprepareHeader=XPROXY_168,@169")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_169 { {0xFF, 0x25}, (void*)&XPROXY_169.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_169=_XPROXY_169")
#pragma comment(linker, "/EXPORT:waveOutBreakLoop=XPROXY_169,@170")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_170 { {0xFF, 0x25}, (void*)&XPROXY_170.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_170=_XPROXY_170")
#pragma comment(linker, "/EXPORT:waveOutClose=XPROXY_170,@171")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_171 { {0xFF, 0x25}, (void*)&XPROXY_171.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_171=_XPROXY_171")
#pragma comment(linker, "/EXPORT:waveOutGetDevCapsA=XPROXY_171,@172")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_172 { {0xFF, 0x25}, (void*)&XPROXY_172.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_172=_XPROXY_172")
#pragma comment(linker, "/EXPORT:waveOutGetDevCapsW=XPROXY_172,@173")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_173 { {0xFF, 0x25}, (void*)&XPROXY_173.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_173=_XPROXY_173")
#pragma comment(linker, "/EXPORT:waveOutGetErrorTextA=XPROXY_173,@174")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_174 { {0xFF, 0x25}, (void*)&XPROXY_174.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_174=_XPROXY_174")
#pragma comment(linker, "/EXPORT:waveOutGetErrorTextW=XPROXY_174,@175")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_175 { {0xFF, 0x25}, (void*)&XPROXY_175.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_175=_XPROXY_175")
#pragma comment(linker, "/EXPORT:waveOutGetID=XPROXY_175,@176")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_176 { {0xFF, 0x25}, (void*)&XPROXY_176.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_176=_XPROXY_176")
#pragma comment(linker, "/EXPORT:waveOutGetNumDevs=XPROXY_176,@177")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_177 { {0xFF, 0x25}, (void*)&XPROXY_177.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_177=_XPROXY_177")
#pragma comment(linker, "/EXPORT:waveOutGetPitch=XPROXY_177,@178")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_178 { {0xFF, 0x25}, (void*)&XPROXY_178.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_178=_XPROXY_178")
#pragma comment(linker, "/EXPORT:waveOutGetPlaybackRate=XPROXY_178,@179")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_179 { {0xFF, 0x25}, (void*)&XPROXY_179.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_179=_XPROXY_179")
#pragma comment(linker, "/EXPORT:waveOutGetPosition=XPROXY_179,@180")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_180 { {0xFF, 0x25}, (void*)&XPROXY_180.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_180=_XPROXY_180")
#pragma comment(linker, "/EXPORT:waveOutGetVolume=XPROXY_180,@181")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_181 { {0xFF, 0x25}, (void*)&XPROXY_181.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_181=_XPROXY_181")
#pragma comment(linker, "/EXPORT:waveOutMessage=XPROXY_181,@182")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_182 { {0xFF, 0x25}, (void*)&XPROXY_182.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_182=_XPROXY_182")
#pragma comment(linker, "/EXPORT:waveOutOpen=XPROXY_182,@183")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_183 { {0xFF, 0x25}, (void*)&XPROXY_183.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_183=_XPROXY_183")
#pragma comment(linker, "/EXPORT:waveOutPause=XPROXY_183,@184")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_184 { {0xFF, 0x25}, (void*)&XPROXY_184.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_184=_XPROXY_184")
#pragma comment(linker, "/EXPORT:waveOutPrepareHeader=XPROXY_184,@185")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_185 { {0xFF, 0x25}, (void*)&XPROXY_185.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_185=_XPROXY_185")
#pragma comment(linker, "/EXPORT:waveOutReset=XPROXY_185,@186")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_186 { {0xFF, 0x25}, (void*)&XPROXY_186.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_186=_XPROXY_186")
#pragma comment(linker, "/EXPORT:waveOutRestart=XPROXY_186,@187")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_187 { {0xFF, 0x25}, (void*)&XPROXY_187.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_187=_XPROXY_187")
#pragma comment(linker, "/EXPORT:waveOutSetPitch=XPROXY_187,@188")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_188 { {0xFF, 0x25}, (void*)&XPROXY_188.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_188=_XPROXY_188")
#pragma comment(linker, "/EXPORT:waveOutSetPlaybackRate=XPROXY_188,@189")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_189 { {0xFF, 0x25}, (void*)&XPROXY_189.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_189=_XPROXY_189")
#pragma comment(linker, "/EXPORT:waveOutSetVolume=XPROXY_189,@190")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_190 { {0xFF, 0x25}, (void*)&XPROXY_190.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_190=_XPROXY_190")
#pragma comment(linker, "/EXPORT:waveOutUnprepareHeader=XPROXY_190,@191")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_191 { {0xFF, 0x25}, (void*)&XPROXY_191.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_191=_XPROXY_191")
#pragma comment(linker, "/EXPORT:waveOutWrite=XPROXY_191,@192")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_192 { {0xFF, 0x25}, (void*)&XPROXY_192.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_192=_XPROXY_192")
#pragma comment(linker, "/EXPORT:wid32Message=XPROXY_192,@193")
extern "C" DLLPROXY_ALIGN(DefaultFuncAlign) __declspec(allocate(".dllprox$b"))
DLLPROXY_CONSTINIT X86Stub XPROXY_193 { {0xFF, 0x25}, (void*)&XPROXY_193.TargetAddress, (void*)&UnresolvedExportCallback, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC} };
#pragma comment(linker, "/ALTERNATENAME:XPROXY_193=_XPROXY_193")
#pragma comment(linker, "/EXPORT:wod32Message=XPROXY_193,@194")


// 代理生成统计: 总导出数=193, 代理函数=193, 转发函数=0, 数据转发=0